package edu.iiitb.facebook.action.messages;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;

import org.apache.struts2.interceptor.SessionAware;

import com.opensymphony.xwork2.ActionSupport;

import edu.iiitb.facebook.action.dao.impl.MessageDAOImpl;
import edu.iiitb.facebook.action.model.Message;
import edu.iiitb.facebook.action.model.User;
import edu.iiitb.facebook.util.Constants;

public class ReplyAction extends ActionSupport implements SessionAware
{
	private static final long serialVersionUID = 1218149774198859476L;

	private Message replyMsg;
	private Map<String, Object> session;
	
	/**
	 * Send reply
	 * 
	 * @return
	 */
	public String reply()
	{
		User thisUser = (User)(session.get(Constants.USER));
		
		// message id is generated by the db
		// conversation id and message  text are set by the view
		// sentAt is generated by the db
		// inbox is set by dao while inserting for all participants
		// readStatus is set by dao while inserting for all participants
		replyMsg.setSender(thisUser.getUserId());
		replyMsg.setSenderFirstName(thisUser.getFirstName());
		replyMsg.setSenderLastName(thisUser.getLastName());

		new MessageDAOImpl().insertIntoExistingConversation(replyMsg);
		
		// post processing
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
	    replyMsg.setSentAt(sdf.format(new Date()));

		return SUCCESS;		
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.apache.struts2.interceptor.SessionAware#setSession(java.util.Map)
	 */
	@Override
	public void setSession(Map<String, Object> arg0)
	{
		this.session = arg0;
	}

	public Message getReplyMsg()
	{
		return replyMsg;
	}

	public void setReplyMsg(Message replyMsg)
	{
		this.replyMsg = replyMsg;
	}
}
